# Generated by Django 3.2.5 on 2021-07-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='date',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='file',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='time',
        ),
        migrations.AlterField(
            model_name='contactus',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
