# Generated by Django 3.2.5 on 2021-10-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_alter_rate_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='buy',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='rate',
            name='sale',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
