# Generated by Django 3.2.5 on 2021-08-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_rateus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='rateus',
            name='grade',
            field=models.PositiveIntegerField(),
        ),
    ]
