# Generated by Django 3.2.5 on 2021-10-22 07:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_auto_20211006_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 22, 7, 49, 37, 484333, tzinfo=utc)),
        ),
    ]
