# Generated by Django 3.2.5 on 2021-08-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0004_auto_20210812_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='source_url',
            field=models.CharField(max_length=255),
        ),
    ]
