# Generated by Django 3.2.5 on 2021-08-22 09:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0007_auto_20210820_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='email',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='name',
        ),
        migrations.AddField(
            model_name='rate',
            name='buy',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='rate',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rate',
            name='curr_type',
            field=models.CharField(default='None', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rate',
            name='sale',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='rate',
            name='source',
            field=models.CharField(default='None', max_length=32),
            preserve_default=False,
        ),
    ]
