# Generated by Django 3.2.5 on 2021-09-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0010_responselog_response_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='curr_type',
            field=models.CharField(choices=[('USD', 'Dollar'), ('EUR', 'Euro')], max_length=3),
        ),
    ]
