# Generated by Django 3.2.5 on 2021-09-13 09:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0011_alter_rate_curr_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='responselog',
            name='request_method',
            field=models.CharField(choices=[('GET', 'GET method'), ('POST', 'POSR method')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
